test:
 adapter: mysql2
 host: localhost
 username: root
 password: ''
 reconnect: true
 socket:
 database: beerwars_test

development:
 adapter: mysql2
 host: localhost
 username: root
 password: ''
 reconnect: true
 socket:
 database: beerwars_development