development:
  adapter: postgresql
  encoding: unicode
  database: beerwars_development
  pool: 5
  username: admin
  password:

  test:
    adapter: postgresql
    encoding: unicode
    database: beerwars_test
    pool: 5
    username: admin
    password: